version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: pruebashotel
    networks:
      - minetwork
    ports:
      - 5432:5432
  tomcat:
    image: tomcat:latest
    volumes:
      - ./WebApps/java:/usr/local/tomcat/webapps
    ports:
      - 7777:8080
    depends_on:
      - db
    networks:
      - minetwork
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8890:8899
    depends_on:
      - db
    networks:
      - minetwork

networks:
  minetwork:
